SELECT 
    EXCURSION.FECHA, 
    GRADO.GRADO, 
    GRADO.SECCION, 
    'Alumno' AS Tipo, 
    alumnos.APELLIDO, 
    alumnos.NOMBRE
FROM EXCURSION
JOIN GRADO ON EXCURSION.IdGRADO = GRADO.IdGRADO
JOIN alumnos ON EXCURSION.IdEXCURSION = alumnos.IdEXCURSION
WHERE EXCURSION.FECHA like '2024-10-24'

UNION ALL

SELECT 
    EXCURSION.FECHA, 
    GRADO.GRADO, 
    GRADO.SECCION, 
    'Acompañante' AS Tipo, 
    acompanantes.APELLIDO, 
    acompanantes.NOMBRE
FROM EXCURSION
JOIN GRADO ON EXCURSION.IdGRADO = GRADO.IdGRADO
JOIN acompanantes ON EXCURSION.IdEXCURSION = acompanantes.IdEXCURSION
WHERE EXCURSION.FECHA like '2024-10-24';
